name: Docker Nginx Build & Run

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-run-nginx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nginx-demo .

      - name: List Docker images
        run: docker images

      - name: Run Nginx container
        run: |
          docker run -d -p 8080:80 --name nginx-demo-container nginx-demo
          docker ps -a

