name: Docker Nginx Build & Logs

on:
  workflow_dispatch:

jobs:
  build-run-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nginx-demo .

      - name: Run Nginx container
        run: docker run -d -p 8080:80 --name nginx-demo-container nginx-demo

      - name: List running containers
        run: docker ps

      - name: Show container logs
        run: docker logs nginx-demo-container

